### ISSUE TITLE
nuxt-link and imports are not considering stage path `/dev`

### ISSUE THREAD

**Issue by sergiofilhowz** [wan2land/serverless-nuxt#2]
When I click a nuxt-link, I get redirected to the rootpath plus `nuxt-link.to` and it is removing the `/dev` stage path

Same happens to client imports

```GET https://XXXX.execute-api.us-east-1.amazonaws.com/_nuxt/6dbafefff73a2f76381d.js net::ERR_ABORTED 403```

**Comment by sergiofilhowz** [comment]
Example: I navigate to root url ```https://XXXX.execute-api.us-east-1.amazonaws.com/dev```

And theres a 
```xml
<nuxt-link to="/details">Click to see details</nuxt-link>
```

It will redirect to:
```https://XXXX.execute-api.us-east-1.amazonaws.com/details```

**Comment by wan2land** [comment]
Connecting the domain solves it.

(I recommend using a plugin such as [serverless-domain-manager](https://www.npmjs.com/package/serverless-domain-manager.))

Full support for Prefix problem requires to touch the Nuxt core sources. But, It is much easier to use domains.
