### ISSUE TITLE
Dependencies not removed

### ISSUE THREAD

**Issue by hmaesta** [wan2land/serverless-nuxt#219]
What should be the expected content on the zip file under `.serverless`? 

Mine is my full souce – incluindo everything on `node_modules` and `.nuxt`.

Shouldn't it be only `.nuxt/dist/client`?

My package.json is [very lightweight](https://bundlephobia.com/scan-results?packages=@braid/vue-formulate@2.4.3,@braid/vue-formulate-i18n@1.12.0,@jaames/iro@5.2.3,@nuxt/components@1.1.0,@nuxtjs/axios@5.12.2,@nuxtjs/svg@0.1.12,@tailwindcss/ui@0.6.0,cookie-universal-nuxt@2.1.4,date-fns-tz@1.0.10,flatpickr@4.6.6,frappe-charts@1.5.2,imask@6.0.5,nuxt-clipboard2@0.2.1,nuxt-i18n@6.14.2,nuxt-start@2.14.7,serverless-nuxt@1.1.1,standard@14.3.4,string-similarity@4.0.2,tailwindcss@1.8.10,v-tooltip@2.0.3,vue-flatpickr-component@8.1.6,vue-formulate-extended@1.1.1,vue-inline-svg@2.0.0,vue-js-modal@2.0.0-rc.6,vue-toastification@1.7.6,vue-unicons@2.3.0,vue2-frappe@1.2.3,vuex-cache@3.3.0&sortMode=size), but the .zip sent to AWS has over 110 MB (because of `node_modules`)

I tried some custom settings on `serverless.yml` (like package exlude/include) but everything I get that `nuxt-start` were not found.

Any suggestions?

**Comment by wan2land** [comment]
in my case,

`.serverless` directory

```
cloudformation-template-create-stack.json
cloudformation-template-update-stack.json (or not)
serverless-state.json
project-name.zip
```

`.serverless/project-name.zip` directory

```
.next/**
node_modules/**

...(nuxt root directories like below)...
assets/**
modules/**
pages/**
plugins/**

package.json
package-lock.json
nuxt.config.js

handler.js (lambda entry file)
```

**Comment by wan2land** [comment]
If it exceeds 110MB, it is most likely a font or image.

All static files created after webpack build in the plugin are uploaded to s3.

1.  When installing font or image related packages by npm, run it with the \`--dev\` option.
2.  If you use image or font files under `/static`, please move them all under `/assets`. And when using in vue, please use the path using webpack.

**Example in CSS**

```css
.something {
  background-image: url(~assets/images/something.png);
}
```

**Example in Vue**

```
<template>
  <!-- <img src="/static/something.png" /> -->
  <img :src="require('~/assets/images/something.png')" />
</template>
```

**Comment by alexcroox** [comment]
@hmaesta the issue with all these Nuxt lambda helpers is they don't seem to be tested with real world applications of a reasonable size. If you add a bunch of deps that are huge but tree-shaken small during a nuxt build, you still can't upload your package to Lambda because it contains the raw node_modules versions which quickly hit the 50MB limit on any reasonably complex project.

**Comment by wan2land** [comment]
One more,

`serverless.yml`

```yaml
package:
  exclude:
    - assets/**
    - components/**
    - pages/**
    - node_modules/**/*.ts
    - node_modules/**/*.ts.map
    - node_modules/**/*.js.map
    - node_modules/**/*.css.map
```
