### ISSUE TITLE
it's not supported Nuxt Typescript

### ISSUE THREAD

**Issue by soronto3603** [wan2land/serverless-nuxt#234]
I have developed my app using Nuxt Typescript.
and then would deploy using 'serverless-nuxt'. It's not working

I found this.
https://github.com/wan2land/serverless-nuxt/blob/master/packages/serverless-nuxt-plugin/src/index.js#L8

there's not exist script for typescript build

I would like that 'serverless-nuxt' would be support Nuxt Typescript

**Comment by wan2land** [comment]
please show me your `serverless.yml` and `package.json` `dependencies`.

what was the command you wrote in the terminal?

**Comment by wan2land** [comment]
Except for the `nuxt.config.js` file, TypeScript works fine. :smile: 

`nuxt.config.ts` file will be supported in the future.

**Comment by wan2land** [comment]
Please use serverless-nuxt-plugin@1.4.0 or later.
