### ISSUE TITLE
Getting 404 all the time

### ISSUE THREAD

**Issue by goors** [wan2land/serverless-nuxt#261]
I am getting 404, on any page. I know for example login exists. I was asking my self is serverless-nuxt can be used with universal and not just spa?

**Comment by wan2land** [comment]
Of course, it supports universal mode.

Check your domain settings.

[https://github.com/wan2land/serverless-nuxt/blob/master/docs/installation.md#domain-settings](https://github.com/wan2land/serverless-nuxt/blob/master/docs/installation.md#domain-settings)
