### ISSUE TITLE
Feature suggestion: A way to bypass the Nuxt build

### ISSUE THREAD

**Issue by ffxsam** [wan2land/serverless-nuxt#299]
In some cases, the deployment to AWS fails, and so we don't want to go through the Nuxt build process again. It would be cool if there were some way to pass a flag (not sure if `sls deploy` lets you do this) so that the plugin skips the Nuxt build.

**Comment by wan2land** [comment]
serverless-nuxt-plugin 1.4.0 deployed.

check [https://github.com/wan2land/serverless-nuxt/blob/main/docs/installation.md#deploy-without-build](https://github.com/wan2land/serverless-nuxt/blob/main/docs/installation.md#deploy-without-build) :-)

**Comment by ffxsam** [comment]
@wan2land Awesome, thank you!
